name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and deploy
        run: |
          git config --global user.name "nicolasrp432"
          git config --global user.email "nicolasrp432@gmail.com"
          git subtree push --prefix dist origin gh-pages
